partitioner:
  client_num: 100
  test_ratio: 0.2
  seed: 2077
  major_class_num: 1
  dirichlet_alpha: 0.3
  dirichlet_min: 2
  lognormal_sgm: 0.1
  shard_num: 2
trainer:
  verbose: True
  cache_size: 10
  actor_num: 10
  seed: 2077
  round: 100
  sample_rate: 0.1
  batch_size: 32
  epoch: 5
  test_step: 5
  opt:
#    max_grad_norm: 10
    lr: 0.002
  #  momentum: 0.99
  #  dampening: 0
  #  weight_decay: 0.01
  #  nesterov: True
  avgm:
    beta: 0.5
  cfl:
    eps_1: 0.035
    eps_2: 0.4
  ring:
    rho: 0.5
  prox:
    alpha: 0.01
  dyn:
    alpha: 0.01
  la:
    beta: 0.5
    eps: 0.02
    delay_step: 0
  seq:
    size: 3
  sem:
    group_num: 2
    alpha: 0.01
  ifca:
    group_num: 2
  group:
    group_num: 2
    pre_ratio: 0.4
    pre_epoch: 20
  scaffold:
    glr: 0.98


