#数据集
dataset:
#  name: synthetic
  name: mnist
  fds:
    args:
      part: 6
      client_num: 100
      test_ratio: 0.2
      seed: 2077
      major_class_num: 1
      dirichlet_alpha: 0.4
      dirichlet_min: 2
      lognormal_sgm: 0.1
      shard_num: 2
#模型
model:
#  name: SyntheticMLP
  name: MnistMLP
  args:
#    num_classes: 10
#    output_dim : 5
#训练器
trainer:
  names:
#    - FedAvg
#    - FedProx
#    - FedOpt
#    - FedAvgM
#    - Scaffold
#    - FedDyn
#    - FedLA
#    - FedMR
    - FedSem
    - IFCA
    - FedGroup
    - CFL
    - FedCluster

  args:
    tag: _0.002_500
    cache_size: 10
    actor_num: 10
    seed: 2077
    round: 500
    sample_rate: 0.1
    batch_size: 32
    epoch: 5
    test_step: 5
    opt:
      lr: 0.002
    #  momentum: 0.99
    #  dampening: 0
    #  weight_decay: 0.01
    #  nesterov: True
    max_grad_norm: 10
    avgm:
      beta: 0.5
    prox:
      alpha: 0.00025
    adp:
      global_opt: AdaGrad
    dyn:
      alpha: 0.01
    scaffold:
      glr: 0.98
    la:
      beta: 0.6
      eps: 0.035
      delay_step: 0
    mr:
      sync_idx: 2
    sem:
      group_num: 2
      alpha: 0.0
    ifca:
      group_num: 2
    group:
      group_num: 2
      init_args:
        sample_rate: 0.4
        epoch: 30
    cfl:
      eps_1: 0.03
      eps_2: 0.4
    cluster:
      group_num: 10


