seed: 2077
dataset:
#  root: D:/Project/Python/dataset/sent140/raw
  root: /home/ncut/Workbase/dataset/sent140/raw
  glove: /home/ncut/Workbase/dataset/glove
partitioner:
  client_num: 100
model:
  lr: 0.01
trainer:
  actor_num: 10
  group_num: 2
  round: 5
  selected_num: 10
  batch_size: 32
  epoch: 1
  test:
    step: 5
    ratio: 0.2
    batch_size: 512
cfl:
  eps_1: 0.035
  eps_2: 0.5




